### ISSUE TITLE
Some commands have undefined type objects.

### ISSUE THREAD

**Issue by yukad2** [RyotaUnzai/Autodesk-Maya-Python-IntelliSense#12]
## 問題点 1
double, Boolean, Intが定義されていません。
doubleは各所、Booleanは`applyMetadata()`で出てきます。
Intは`evaluationManager()`で出てきます。
（Boolean, Intはドキュメントの不備かもしれませんが）

## 問題点 2
Listオブジェクトを返す各種メソッドが、定義されていない型のオブジェクトを返しています。

例：
```python
def pointPosition(local: boolean, world: boolean) -> float[]:
```

正しくは、
```python
from typing import List
def pointPosition(local: boolean, world: boolean) -> List[float]:
```
とします。（3.9以降なら、`list[float]` でも可）

## 修正が必要な部分
```
double
Boolean
Int
float[]
double[]
boolean[]
selectionItem[] #selectionItem自体も未定義、polyUVOverlap()など
```

**Comment by RyotaUnzai** [comment]
新しく型の定義を追加しました。また、Maya2023がPython 3.9.7のため、float[]などlistで返す形式はlist[<type>]で解決しました。Python3.8およびMaya2022以下に関しては、Autodeskのサポートからも外されていくことを考え、今後も対応する予定はありません。記述方式もできるだけ最新の形で定義していきます。対応していないバージョンなどでは__future__ などを使って新しい定義方式に対応していきます。
