### ISSUE TITLE
Please add ...(Ellipsis) for all arguments and add *args for all methods.

### ISSUE THREAD

**Issue by yukad2** [RyotaUnzai/Autodesk-Maya-Python-IntelliSense#15]
## 問題点 1
引数がすべて必須引数なので、型チェックを有効化すると、引数が不足していることを表す、
`Argument missing for parameter " "` が出ます。

## 解決方法 1
`= ...`(Ellipsis) を追加します。
```python
def error(noContext: boolean = ..., showLineNumber: boolean = ...) -> None:
```

## 問題点 2
可変長引数が定義されていないので、キーワードのない引数を与えると、1つ目のキーワードの引数として扱われてしまいます。
`cmds.error("test") # -> 型チェックで、"test"がnoContext: booleanとして扱われる`

## 解決方法 2
`*args`を追加します。
```python
def error(*args, noContext: boolean, showLineNumber: boolean) -> None:
```

**Comment by RyotaUnzai** [comment]
https://github.com/RyotaUnzai/Autodesk-Maya-Python-IntelliSense/pull/17 をマージしたので解決済みにしておきます
