### ISSUE TITLE
Doesn't work absolute import in cmds/__init__.py

### ISSUE THREAD

**Issue by yukad2** [RyotaUnzai/Autodesk-Maya-Python-IntelliSense#8]
## 問題点 1
生成される `typings/maya/cmds/__init__.py` で、各 `mayacmds_*.py`を絶対インポートしているため、`typings` までしかパスが通っていない場合、各 `mayacmds_*.py` まで参照が届きません。
配布物の使用例のように、workspace以下に配置する場合は問題ないと思いますが、任意の場所に配置して、extraPaths に追加すると動作しません。

## 解決方法 1
`maya.cmds` からの絶対インポートにします。(vscode-mayapyはこの形式です)
```
- from mayacmds_a import *
+ from maya.cmds.mayacmds_a import *
```

## 解決方法 2
相対インポートにします。
```
- from mayacmds_a import *
+ from .mayacmds_a import *
```

**Comment by RyotaUnzai** [comment]
報告ありがとうございます
対応します！
